### ISSUE TITLE
SimpleCredsAuth hard-codes uid/gid 0 as default

### ISSUE THREAD

**Issue by tiran** [latchset/custodia#116]
The hard-coded defaults for uid and gid give root implicit access to secrets. I would prefer to have another default, e.g. ```None```, which means no access for any user by default.

**Comment by simo5** [comment]
I am not sure what would be the point of setting None, if you do not want to give access to anyone you can simply omit SimpleCredsAuth. Otherwise defaulting to root seem fine given root can always change uid to any user in the system anyway.

**Comment by tiran** [comment]
Use case:

```
uid = heimes
```

I only want user ```heimes``` to be allowed to auth, neither user root nor other members of group ```heimes``` or any other group.

**Comment by simo5** [comment]
ok so you want the defaulg gid to be -1 and if -1 is found than no matching on gid is performed only uid (or vice versa), I am ok with this.

**Comment by tiran** [comment]
```-1``` sounds like a good idea. I'll create a PR tomorrow.
