### ISSUE TITLE
Add support for old setuptools version

### ISSUE THREAD

**Issue by tiran** [latchset/custodia#129]
Old setuptools versions do not support features like ```EntryPoint().resolve()``` and ```':python_version<"3.4"': ['configparser']```. For resolve, add workaround ```ep.resolve() if hasattr(ep, "resolve") else ep.load(require=False)```. For version pinning, add the same workaround as FreeIPA ```ipasetup.py``` for ```setuptools < 18.0```.

**Comment by raildo** [comment]
Do you have a link for the FreeIPA workaround? It would make easy to validate the same solution. :)

**Comment by tiran** [comment]
* https://hynek.me/articles/conditional-python-dependencies/
* https://github.com/pyca/cryptography/issues/2838
* https://github.com/freeipa/freeipa/blob/master/ipasetup.py.in
