### ISSUE TITLE
KEM requests with whitespace in key name fail

### ISSUE THREAD

**Issue by tiran** [latchset/custodia#135]
The issue was discovered by @MartinBasti in FreeIPA https://github.com/freeipa/freeipa/pull/517#issuecomment-288370660 . @adelton reported the same bug a while ago on bugzilla (can't find it right now).

See PR #134 for a reproducer.

```
HTTPError: 400 Client Error: Key name kem/key%20with%20space does not match subject kem/key with space for url: http+unix://.%2ftests%2ftmp%2ftest_socket/enc/kem/key%20with%20space
```

**Comment by adelton** [comment]
> (can't find it right now)

Could it be https://bugzilla.redhat.com/show_bug.cgi?id=1411810?

**Comment by tiran** [comment]
Simo and I came to an agreement how to fix the issue. Custodia no longer url-decodes the URL keys because we ran into issues with url-encoded slash (```/```). To fix the problem with white spaces in keys, ```check_kem_claims``` should compare url-encoded claim sub with name.
