### ISSUE TITLE
store: API for unsupported operation

### ISSUE THREAD

**Issue by tiran** [latchset/custodia#158]
The store API does not provide an API to indicate that an operation is not supported. In ```IPAVault``` I'm currently raising ```CSStoreError```, which is turned into a HTTP 500 error. 

Use cases:

* ```IPAVault``` plugin does not offer ```span``` because IPA Vault has no concept of containers. It's a key/value store with a flat namespace.
* A read-only store does not provide ```set``` or ```span```.

**Comment by tiran** [comment]
Related to that, ```IPAVault``` and ```IPACertReq``` would benefit from exceptions to signal results like *not allowed* and *operation failed*.

**Comment by JAORMX** [comment]
@tiran What do you suggest on using? a 403 or a 405 instead?

If no other choice, I'm particularly keen on 418 😛

**Comment by tiran** [comment]
@JAORMX The storage layer should not deal with HTTP status codes at all. We should define a bunch of additional exceptions. The pipeline then maps the storage exceptions to HTTP status codes.

**Comment by simo5** [comment]
Yes please add CSStoreUnsupported or similar

**Comment by raildo** [comment]
I can see two ways to fix this issue:
1- Custodia create an exception in each API call to be "prepared" to be raised by any client, like custodia.ipa. So, all the API calls will be enabled and the responsibility to unsupported a specific API call will be on the client instance.

2- Custodia create a config session to enabled/disable API calls, so the responsibility to mark an API call as unsupported will be only on Custodia, but we will not be able to have different behaviors for n-clients using the same Custodia Instance.

Do you guys agree with this two ways, we should follow one of them?
