### ISSUE TITLE
Make key container creation idempotent

### ISSUE THREAD

**Issue by mbarnes** [latchset/custodia#206]
`POST /secrets/mycontainer` returns a 409 Conflict if `mycontainer` already exists.  But since the request doesn't take any additional parameters, there's really no conflict.

I suggest instead returning a 200 OK to make the API a bit more "RESTful".  Users could still distinguish whether the container already existed by checking for 200 OK vs 201 Created.

**Comment by simo5** [comment]
sounds like a good idea
