### ISSUE TITLE
Create general SQL store with SQLAlchemy

### ISSUE THREAD

**Issue by tiran** [latchset/custodia#44]
Custodia has no general API to talk to arbitrary SQL databases like Postgres or MySQL. The preferred store is sqlite. In the future we might want to store data in another database. SQLAlchemy is the most powerful framework and SQL DB abstraction for Python.

NOTE: The forking model of Custodia makes it impossible to use some optimization like SQLAlchemy's connection pool and persistent connections. Engines are not fork-safe http://docs.sqlalchemy.org/en/latest/core/connections.html#basic-usage

**Comment by simo5** [comment]
I am going to close this one as custodia uses forking firght now and will do for the forseable future and sql alchemy doesn't work there
