### ISSUE TITLE
Create SELinux policy for custodia

### ISSUE THREAD

**Issue by tiran** [latchset/custodia#56]
## Custodia server
- config /etc/custodia/
- logs /var/log/custodia/
- var dir /var/lib/custodia/
- bind to Unix stream socket /var/run/custodia.sock
- bind to any TCP socket
- connect to any TCP socket
- fork
- read /proc/pid/cgroup
- read /proc/pid/loginuid
- units  /usr/lib/systemd/system/custodia.service,  /usr/lib/systemd/system/custodia.socket
## IPA clients
- allow any program to connect to Custodia's sockets (TCP, Unix)
## ipa custodia (FreeIPA)
- config /etc/ipa/custodia/
- log /var/log/ipa-custodia.audit.log
- bind to Unix stream socket /var/run/httpd/ipa-custodia.sock
- connect to /var/run/slapd-*.socket (LDAPI)
- /usr/lib/systemd/system/ipa-custodia.service
- cert stores https://github.com/freeipa/freeipa/blob/master/ipaserver/secrets/store.py#L249
  - /etc/pki/pki-tomcat/alias
  - /var/lib/ipa/ra-agent.pem
  - /var/lib/ipa/ra-agent.key
  - ~~/etc/httpd/alias~~

## sepolgen

[custodia_sepolgen.tar.gz](https://github.com/latchset/custodia/files/432628/custodia_sepolgen.tar.gz)

**Comment by simo5** [comment]
We should leave this to downstream distributions probably as each one can define policies differently

**Comment by tiran** [comment]
I have moved the custodia SELinux policies to https://github.com/latchset/custodia-selinux
