### ISSUE TITLE
Don't run daemon as root

### ISSUE THREAD

**Issue by tiran** [latchset/custodia#57]
The Custodia daemon runs with root privileges. There is really no reason to require root except for some experimental Docker code which is going to be replaced.
- custodia.sock can be moved to a directory that is owned by a custodia user.
- /proc/PID/cgroup and /proc/PID/loginuid are world-readable

ipa-custodia still needs to run as root because it has to read files like NSSDBs of 389-DS and Dogtag PKI.

**Comment by simo5** [comment]
I think this should be left as a configuration option.
systemd can start sevices under a specific user directly, so if you provide a suitable configuartion file and unit file you can already run custodia as non root. In fact that's what we do in make test.
With socket activation we do not need root to bind to privieged ports either, so if you agree I'd close this as a non-issue.
