### ISSUE TITLE
Path unquoting

### ISSUE THREAD

**Issue by tiran** [latchset/custodia#60]
Why does custodia.http.server unquotes the request's path? This breaks ```PUT /secrets/docker/http%3A%2F%2Flocalhost%3A5000``` because it unquotes it to ```http://localhost:5000``` and then treats ```http:/``` as a path segment.

**Comment by simo5** [comment]
I don't know why, looks like a bug.

**Comment by tiran** [comment]
I first tried to change path to a list of path segments. It was an intrusive change that made the authorizers even harder to understand. PR #64 implements a much simpler fix.

**Comment by tiran** [comment]
I don't have a good fix that keeps backwards compatibility with existing plugins. For now I suggest that we don't support quoted strings and limit the character of path segments set to ```[a-zA-Z0-9-_=+.]``` plus ```/``` as path segment separator.

**Comment by simo5** [comment]
I would just remove unquoting and not set artificial limits for now.
