### ISSUE TITLE
SimpleAuthKeys uses 'header' option for two fields

### ISSUE THREAD

**Issue by tiran** [latchset/custodia#66]
This doesn't look right:
```
self.id_header = self.config.get('header', 'CUSTODIA_AUTH_ID')
self.key_header = self.config.get('header', 'CUSTODIA_AUTH_KEY')
```

**Comment by simo5** [comment]
What's wrong with it ?

**Comment by simo5** [comment]
Ah now that I see the code indeed ... not sure how to fix this, perhaps we should not make it configurable at all and provide a new class for arbitrary headers that uses id_header and key_header as options.

**Comment by tiran** [comment]
How about we rename the options to id_header and key_header? It's a low-risk change. The config options were broken from the beginning.

**Comment by simo5** [comment]
sounds good
