### ISSUE TITLE
Check travis pep8 configuration

### ISSUE THREAD

**Issue by simo5** [latchset/custodia#73]
Seem like travis does not catch out of order import issues, investigate if a plugin is missing there

**Comment by tiran** [comment]
The flake8-import-order gets installed. On my machine the tests are also passing with flake8-import-order==0.9.2. Please run tox -r (recreate).

```
pep8py3 installed: cffi==1.8.2,cryptography==1.5,custodia==0.2.dev1,flake8==3.0.4,flake8-import-order==0.9.2,idna==2.1,jwcrypto==0.3.1,mccabe==0.5.2,pep8-naming==0.4.1,pyasn1==0.1.9,pycodestyle==2.0.0,pycparser==2.14,pyflakes==1.2.3,requests==2.11.1,six==1.10.0
```

```
pep8py2 installed: cffi==1.8.2,configparser==3.5.0,cryptography==1.5,custodia==0.2.dev1,enum34==1.1.6,flake8==3.0.4,flake8-import-order==0.9.2,idna==2.1,ipaddress==1.0.16,jwcrypto==0.3.1,mccabe==0.5.2,pep8-naming==0.4.1,pyasn1==0.1.9,pycodestyle==2.0.0,pycparser==2.14,pyflakes==1.2.3,requests==2.11.1,six==1.10.0
```

**Comment by tiran** [comment]
For the record: Simo has flake8  2.5.5 with pep8: 1.6.2, import_order 0.6.1.

**Comment by tiran** [comment]
It's not a bug in our configuration. Travis and tox will automagically pick up new versions of the import checker.
